### ISSUE TITLE
About MvTec configuration

### ISSUE THREAD

**Issue by boringKey** [jqtangust/IUF#2]
Hello, this is truly an enlightening work. However, I have noticed that only a sample dataset setting profile for the Visa dataset has been published. Could you please provide an example of the configuration file for the Mvtec dataset as well. Thank you.

**Comment by Karma1628** [comment]
同求，期待！！！

**Comment by jqtangust** [comment]
I have explained the config file, and you can easily edit config files for the MvTec dataset.

For example, for 14-1, you can combine 14 objects for training in the first step and then use the last object for the second step.

**Comment by Karma1628** [comment]
好的，谢谢
