### ISSUE TITLE
About the code for calculating FM and ACC metrics

### ISSUE THREAD

**Issue by tanyux** [jqtangust/IUF#5]
After the test code execution, I only obtained the AUROC metrics for each category and did not see the FM and ACC metrics mentioned in the paper. How can I modify the code to obtain these metrics?

**Comment by jqtangust** [comment]
ACC is considered as the AUROC.

To calculate FM, you should select different steps and average the decrease of all AUROC in each step.

**Comment by FuNz-0** [comment]
ACC是最后一个任务训练完的模型在，所有类别上的AUROC平均数吗
